apiVersion: v1
kind: ConfigMap
metadata:
  name: data-engine-configmap
data:
  config.yaml: |
    data_engine_server_configuration:
      data_engine_server_settings:
        address: '127.0.0.1'
        port: 8000
    
    message_broker_server_configuration:
      message_broker_server_settings:
        address: '127.0.0.1'
        port: 8001

    topics:
      - 'order-data'
      - 'trade-data'
    
    exchanges:
      - exchange: 'Kraken'
        websocket_token: 'https://api.kraken.com/0/private/GetWebSocketsToken'
        symbols:
          - 'BTC/USD'
        apis:
          - websockets:
              - channel: 'level3'
                endpoint: 'wss://ws-auth.kraken.com/v2'
              - channel: 'trade'
                endpoint: 'wss://ws.kraken.com/v2'