apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-engine-deployment
  labels:
    app: data-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-engine
  template:
    metadata:
      labels:
        app: data-engine
    spec:
      containers:
      - name: data-engine
        image: rust:alpine
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_PATH
          value: "/etc/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: data-engine-configmap
          items:
            - key: config.yaml
              path: config.yaml