apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-engine-deployment
  labels:
    app: data-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-engine
  template:
    metadata:
      labels:
        app: data-engine
    spec:
      containers:
      - name: data-engine
        image: data-engine:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_PATH
          value: "/etc/config/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        imagePullPolicy: IfNotPresent
      volumes:
      - name: config-volume
        configMap:
          name: data-engine-configmap
          items:
            - key: config.yaml
              path: config.yaml