apiVersion: v1
kind: Service
metadata:
  name: data-engine-service
  labels:
    app: data-engine
spec:
  selector:
    app: data-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080