apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale
spec:
  selector:
    matchLabels:
      app: data-engine
  serviceName: "timescale"
  replicas: 3
  template:
    metadata:
      labels:
        app: data-engine
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: timescale
        image: timescale/timescaledb:latest-pg16
        ports:
        - containerPort: 32935
          name: timescale
        volumeMounts:
        - name: timescale-storage
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: data-engine-secret
              key: timescale-root-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-engine-secret
              key: timescale-root-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: data-engine-configmap
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: data-engine-configmap
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: data-engine-configmap
              key: POSTGRES_PORT
  volumeClaimTemplates:
  - metadata:
      name: timescale-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi