name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout DataEngine
      uses: actions/checkout@v4
      with:
        path: DataEngine

    - name: Checkout DatabaseEngine
      uses: actions/checkout@v4
      with:
        repository: ItsJustIkenna/DatabaseEngine
        path: DatabaseEngine

    - name: Checkout MessageBrokerEngine
      uses: actions/checkout@v4
      with:
        repository: ItsJustIkenna/MessageBrokerEngine
        path: MessageBrokerEngine

    - name: Build
      run: cd DataEngine/hostbuilder && cargo build --verbose

    - name: Run tests
      run: cd DataEngine/hostbuilder && cargo test --verbose
